name: Joel Fredrick
markdown: redcarpet
highlighter: pygments
paginate: 8
paginate_path: "/page/:num"
excerpt_separator: "<!-- ==== -->"
permalink: /:year/:i_month/:title
exclude:
    - package.json
      gulpfile.js
      node_modules
