name: Joel Fredrick
markdown: redcarpet
pygments: true
paginate: 8
paginate_path: "/page/:num"
excerpt_separator: "<!-- ==== -->"
permalink: /:year/:i_month/:title
exclude:
    - package.json
      Gruntfile.js
      node_modules
